import type { SequenceDataType, SequenceIdentity } from './model.ts';
import { defaultSequenceMax, defaultSequenceMin } from './sequence.ts';

/**
 * Identity column option normalization: a column's `GENERATED … AS IDENTITY` options, as an
 * import or a hand-built model may carry them, to the effective values PostgreSQL would use.
 *
 * The option rules are the sequence rules (see `sequence.ts`): `INCREMENT BY` defaults to `1`;
 * `CACHE` to `1`; `CYCLE` to off. Ascending (`increment > 0`): `MINVALUE` defaults to `1`,
 * `MAXVALUE` to the data type's maximum. Descending: `MINVALUE` defaults to the data type's
 * minimum, `MAXVALUE` to `-1`. `START WITH` defaults to `MINVALUE` when ascending and to
 * `MAXVALUE` when descending. Omitting an option and stating it explicitly mean the engine
 * default, so both normalize to the same identity.
 *
 * PostgreSQL allows an identity column only on `smallint`, `integer`, and `bigint`;
 * `canonicalIntType` resolves an as-written integer type to one of those and rejects every
 * other type. Every numeric option is an exact 64-bit integer in canonical decimal form (see
 * `Identity`), canonicalized with `bigint`, never JavaScript `number`, because the type bounds
 * exceed `Number.MAX_SAFE_INTEGER`.
 */

/** How an identity column generates values: `GENERATED ALWAYS` or `GENERATED BY DEFAULT`. */
export type IdentityGeneration = 'always' | 'by default';

/**
 * Identity options as a source or a caller may state them, before normalization. Every field
 * is optional: an omitted field means the engine default. Values are canonical decimal strings.
 */
export interface IdentityOptions {
  /** The implicit sequence's schema-qualified name, when the source states one. */
  readonly sequenceName?: SequenceIdentity;
  /** The `INCREMENT BY` step; `1` when omitted. */
  readonly increment?: string;
  /** The `MINVALUE`; direction-dependent when omitted. */
  readonly minValue?: string;
  /** The `MAXVALUE`; direction-dependent when omitted. */
  readonly maxValue?: string;
  /** The `START WITH` value; `MINVALUE`/`MAXVALUE` by direction when omitted. */
  readonly start?: string;
  /** The `CACHE` size; `1` when omitted. */
  readonly cache?: string;
  /** Whether the identity's sequence wraps with `CYCLE`; off when omitted. */
  readonly cycle?: boolean;
}

/** An identity's generation mode plus as-stated options: what `effectiveIdentity` accepts. */
export interface IdentityInput extends IdentityOptions {
  /** Whether the column generates `ALWAYS` or `BY DEFAULT`. */
  readonly generated: IdentityGeneration;
}

/**
 * A column's identity and its effective options. Every numeric option is an exact 64-bit
 * integer in canonical decimal form — an optional minus followed by digits, no leading zeros —
 * never a JavaScript `number`: the type bounds exceed `Number.MAX_SAFE_INTEGER`. The values are
 * the effective ones PostgreSQL would use, so an option the source omitted and the same option
 * stated explicitly are the same value here (normalization lives in this module).
 *
 * `sequenceName` is the identity's implicit sequence name, when the source states one.
 */
export interface Identity {
  /** Whether the column generates `ALWAYS` or `BY DEFAULT`. */
  readonly generated: IdentityGeneration;
  /** The implicit sequence's schema-qualified name, when the source states one. */
  readonly sequenceName?: SequenceIdentity;
  /** The `INCREMENT BY` step, an exact integer. */
  readonly increment: string;
  /** The `MINVALUE`, an exact integer. */
  readonly minValue: string;
  /** The `MAXVALUE`, an exact integer. */
  readonly maxValue: string;
  /** The `START WITH` value, an exact integer. */
  readonly start: string;
  /** The `CACHE` size, an exact positive integer. */
  readonly cache: string;
  /** Whether the identity's sequence wraps with `CYCLE`. */
  readonly cycle: boolean;
}

/**
 * Resolves `input`'s options to effective values for an identity column of `dataType`. Numeric
 * strings are canonicalized with `bigint` (`'+1'`, `'01'`, and `'1'` all normalize to `'1'`);
 * an absent option takes its engine default; a present option wins, so normalization is
 * idempotent. The returned identity is an independent copy: mutating it never affects `input`,
 * and `input` is never mutated.
 */
export function effectiveIdentity(dataType: SequenceDataType, input: IdentityInput): Identity {
  const increment = canonical(input.increment ?? '1');
  const minValue = canonical(input.minValue ?? defaultSequenceMin(dataType, increment));
  const maxValue = canonical(input.maxValue ?? defaultSequenceMax(dataType, increment));
  const start = canonical(input.start ?? (isAscending(increment) ? minValue : maxValue));
  const cache = canonical(input.cache ?? '1');
  const cycle = input.cycle ?? false;

  return {
    generated: input.generated,
    ...(input.sequenceName === undefined
      ? {}
      : { sequenceName: copyIdentityName(input.sequenceName) }),
    increment,
    minValue,
    maxValue,
    start,
    cache,
    cycle,
  };
}

/**
 * The identity data type for an as-written integer type, or `undefined` when the type is not an
 * identity column type. Matching is case-insensitive, an optional `pg_catalog.` prefix is
 * stripped, and only the integer spellings map: `smallint`/`int2`, `integer`/`int`/`int4`, and
 * `bigint`/`int8`. Every other type — `numeric`, `text`, a domain, an empty string — is not.
 */
export function canonicalIntType(type: string): SequenceDataType | undefined {
  const lower = type.toLowerCase();
  const name = lower.startsWith('pg_catalog.') ? lower.slice('pg_catalog.'.length) : lower;
  switch (name) {
    case 'smallint':
    case 'int2':
      return 'smallint';
    case 'integer':
    case 'int':
    case 'int4':
      return 'integer';
    case 'bigint':
    case 'int8':
      return 'bigint';
    default:
      return undefined;
  }
}

/** Whether the exact `increment` advances toward increasing values. */
function isAscending(increment: string): boolean {
  return BigInt(increment) > 0n;
}

/** `value` in canonical decimal form: an optional minus followed by digits, no leading zeros. */
function canonical(value: string): string {
  return BigInt(value).toString();
}

/** A copy of `sequenceName`, independent of the caller's payload. */
function copyIdentityName(sequenceName: SequenceIdentity): SequenceIdentity {
  return { schema: sequenceName.schema, name: sequenceName.name };
}
