ALTER TABLE public.users DROP CONSTRAINT users_name_id_fkey;
ALTER TABLE public.users DROP CONSTRAINT users_mail_id_fkey;
ALTER TABLE public.users DROP CONSTRAINT users_pkey;
ALTER TABLE public.users DROP COLUMN legacy;
ALTER TABLE public.users DROP COLUMN name_id;
ALTER TABLE public.users ADD COLUMN created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.users ADD COLUMN event_id bigint;
ALTER TABLE public.users ALTER COLUMN name TYPE text;
ALTER TABLE public.users ALTER COLUMN name SET NOT NULL;
ALTER TABLE public.users ALTER COLUMN email TYPE character varying(24);
ALTER TABLE public.users ADD PRIMARY KEY (id);
ALTER TABLE public.users ADD CONSTRAINT users_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);
ALTER TABLE public.users ADD CONSTRAINT users_mail_id_fkey FOREIGN KEY (mail_id) REFERENCES public.mail(id) ON DELETE CASCADE;
