ALTER TABLE public.e DROP CONSTRAINT e_c_id_fkey;
ALTER TABLE public.f DROP CONSTRAINT f_c_id_fkey;
ALTER TABLE public.q DROP CONSTRAINT q_p_fkey;
ALTER TABLE public.t DROP CONSTRAINT t_parent_id_fkey;
ALTER TABLE public.c DROP CONSTRAINT c_pkey;
ALTER TABLE public.p DROP CONSTRAINT p_pkey;
ALTER TABLE public.t DROP CONSTRAINT t_pkey;
ALTER TABLE public.c ADD CONSTRAINT c_pkey_v2 PRIMARY KEY (id);
ALTER TABLE public.p ADD CONSTRAINT p_pkey_v2 PRIMARY KEY (b, a);
ALTER TABLE public.t ADD CONSTRAINT t_pkey_v2 PRIMARY KEY (id);
ALTER TABLE public.e ADD CONSTRAINT e_c_id_fkey FOREIGN KEY (c_id) REFERENCES public.c(id);
ALTER TABLE public.f ADD CONSTRAINT f_c_id_fkey FOREIGN KEY (c_id) REFERENCES public.c;
ALTER TABLE public.q ADD CONSTRAINT q_p_fkey FOREIGN KEY (pa, pb) REFERENCES public.p(a, b);
ALTER TABLE public.t ADD CONSTRAINT t_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.t(id);
